
###
# Request chart data: count and average price for Audi cars with petrol engine

###
POST https://ehomeho:3000/localhost:3000/charts-data
Content-Type: application/json
Accept: application/json

{
    "make": "Audi",
    "engine": [
        "Petrol"
    ],
    "priceFrom": 0,
    "priceTo": 100000,
    "group": [
        "make",
        "year"
    ],
    "aggregators": [
        "count",
        "avg"
    ],
    "order": [],
    "stat_column": "price_in_eur"
}

###

###
POST https://localhost:3000/statistic
Content-Type: application/json
Accept: application/json

{
  "yearFrom": 2010,
  "yearTo": 2020,
  "ccFrom": null,
  "ccTo": null,
  "group": [
    "make"
  ],
  "aggregators": [
    "count"
  ],
  "order": [
    {
      "column": "make",
      "asc": true
    }
  ],
  "stat_column": "price_in_eur",
  "estimated_price": 0
}


###
POST https://localhost:3000/charts-data
Content-Type: application/json
Accept: application/json

{
    "make": "Audi",
    "engine": [
        "Petrol"
    ],
    "priceTo": 100000,
    "group": [
        "make",
        "year"
    ],
    "aggregators": [
        "count",
        "avg"
    ],
    "order": [
        {
            "column": "count",
            "asc": true
        }
        
    ],
    "stat_column": "price_in_eur"
}