
###
# Request chart data: count and average price for Audi cars with petrol engine

###
POST https://localhost:3000/data-stat
Content-Type: application/json
Accept: application/json

{
  "yearFrom": 2010,
  "yearTo": 2020,
  "group": [
    "year", "engine", "gearbox"
  ],
  "aggregators": [
    "count"
  ],
  "order": [
    {
      "column": "year",
      "asc": true
    }
  ],
  "stat_column": "price_in_eur"
  
}

###

###

###
POST https://localhost:3000/data-stat
Content-Type: application/json
Accept: application/json

{
  "yearFrom": 2010,
  "yearTo": 2020,
  "group": [
    "make"
  ],
  "aggregators": [
    "count"
  ],
  "order": [
    {
      "column": "make",
      "asc": true
    }
  ],
  "stat_column": "price_in_eur"
  
}



### POST request to /chart endpoint
POST https://localhost:3000/data-distribution
Content-Type: application/json

{
  "column": "price_in_eur",
  "filter": {
    "make": "Audi",
    "model": "A8",
    "engine": [
        "Petrol"
    ],
    "order":[]
    
  },
  "all": true,
  "distribution_type": "ByInterval",
  "number_of_bins": 5
}

###
POST https://localhost:3000/data-distribution
Content-Type: application/json

{
  "column": "price_in_eur",
  "filter": {
    "make": "Audi",
    "model": "A8",
    "engine": [
        "Petrol"
    ],
    "yearFrom": 2010,
    "yearTo": 2020,
    "powerFrom": 200,
    "powerTo": 455,
    "mileageFrom": 80000,
    "mileageTo": 150000,
    "order":[]
    
  },
  "all": true,
  "distribution_type": "ByInterval",
  "number_of_bins": 5
}

###
POST https://localhost:3000/data-stat
Content-Type: application/json

{
  "make": "Audi",
  "engine": [
    "Petrol"
  ],
  "group": [
    "make",
    "year"
  ],
  "aggregators": [
    "count",
    "avg",
    "sum"
  ],
  "order": [
    {
      "column": "year",
      "asc": true
    }
  ],
  "stat_column": "price_in_eur"
}