
###
# Request chart data: count and average price for Audi cars with petrol engine

###
POST https://localhost:3000/data-stat
Content-Type: application/json
Accept: application/json

{
    "make": "Audi",
    "engine": [
        "Petrol"
    ],
    "group": [
        "make",
        "year"
    ],
    "aggregators": [
        "count",
        "avg"
    ],
    "order": [],
    "stat_column": "price_in_eur"
}

###

###
POST https://localhost:3000/data-stat
Content-Type: application/json
Accept: application/json

{
  "yearFrom": 2010,
  "yearTo": 2020,
  "ccFrom": null,
  "ccTo": null,
  "group": [
    "make"
  ],
  "aggregators": [
    "count"
  ],
  "order": [
    {
      "column": "make",
      "asc": true
    }
  ],
  "stat_column": "price_in_eur"
  
}


###
POST https://localhost:3000/charts-data
Content-Type: application/json
Accept: application/json

{
    "make": "Audi",
    "engine": [
        "Petrol"
    ],
    "priceTo": 100000,
    "group": [
        "make",
        "year"
    ],
    "aggregators": [
        "count",
        "avg"
    ],
    "order": [
        {
            "column": "count",
            "asc": true
        }
        
    ],
    "stat_column": "price_in_eur"
}


### POST request to /chart endpoint
POST https://localhost:3000/charts-data
Content-Type: application/json

{
  "column": "price_in_eur",
  "filter": {
    "make": "Audi",
    "model": "A8",
    "engine": [
        "Petrol"
    ],
    "group": [],
    "aggregators": [],
    "order":[]
    
  },
  "all": true,
  "distribution_type": "ByInterval",
  "number_of_bins": 5
}