
###
# Post request example

###
POST https://localhost:3000/statistic
Content-Type: application/json
Accept: application/json

{
  "make": "BMW",
  "model": "330",
  "engine": ["Petrol", "Diesel"],
  "gearbox": null,
  "mileageFrom": 50000,
  "mileageTo": 80000,
  "ccFrom": null,
  "ccTo": null,
  "group": [
    "make",
    "engine",
    "year"
  ],
  "aggregators": [
    "count",
    "mean",
    "median",
    "std",
    "avg",
    "rsd",
    "quantile_60",
    "quantile_66",
    "quantile_75",
    "quantile_80",
    "quantile_90",
    "min",
    "max"
  ],
  "order": [
    {
      "column": "make",
      "asc": true
    }
  ],
  "stat_column": "price",
  "estimated_price": 0
}

###

###
POST https://localhost:3000/statistic
Content-Type: application/json
Accept: application/json

{
  "yearFrom": 2010,
  "yearTo": 2020,
  "ccFrom": null,
  "ccTo": null,
  "group": [
    "make"
  ],
  "aggregators": [
    "count"
  ],
  "order": [
    {
      "column": "make",
      "asc": true
    }
  ],
  "stat_column": "price_in_eur",
  "estimated_price": 0
}