
###
# Post request example

###
POST https://localhost:3000/statistic
Content-Type: application/json
Accept: application/json

{
    "make": "Audi",
    "model": null,
    "year": null,
    "engine": [
        "Petrol"
    ],
    "gearbox": null,
    "yearFrom": null,
    "yearTo": null,
    "powerFrom": null,
    "powerTo": null,
    "mileageFrom": null,
    "mileageTo": null,
    "ccFrom": null,
    "ccTo": null,
    "priceFrom": 0,
    "priceTo": 100000,
    "group": [
        "make",
        "year"
    ],
    "aggregators": [
        "count",
        "avg"
    ],
    "order": [],
    "stat_column": "price_in_eur",
    "estimated_price": null
}

###

###
POST https://localhost:3000/statistic
Content-Type: application/json
Accept: application/json

{
  "yearFrom": 2010,
  "yearTo": 2020,
  "ccFrom": null,
  "ccTo": null,
  "group": [
    "make"
  ],
  "aggregators": [
    "count"
  ],
  "order": [
    {
      "column": "make",
      "asc": true
    }
  ],
  "stat_column": "price_in_eur",
  "estimated_price": 0
}

###
POST https://localhost:3000/json
Content-Type: application/json
Accept: application/json

{
    "make": "Aston Martin",
    "model": null,
    "search": null,
    "gearbox": null,
    "yearFrom": null,
    "yearTo": null,
    "powerFrom": null,
    "powerTo": null,
    "mileageFrom": null,
    "mileageTo": null,
    "ccFrom": null,
    "ccTo": null,
    "priceFrom": null,
    "priceTo": null,
    "saveDiffFrom": null,
    "saveDiffTo": null,
    "createdOnFrom": null,
    "createdOnTo": null,
    "order": [{"column": "price", "asc": true}],
    "engine": [],
    "aggregators": [],
    "group": []
}

###
POST https://localhost:3000/calculator
Content-Type: application/json
Accept: application/json

{
    "make": "Audi",
    "model": "A4",
    "year": 2018,
    "engine": ["Diesel", "Petrol"],
    "mileage": 55000,
    "power": 150,
    "aggregators": [],
    "group": [],
    "order": [],
    "stat_column": "price_in_eur"
}